server:
port: 8080

spring:
application:
name: stockExchange
datasource:
url: jdbc:mariadb://localhost:3306/stock
username: root
password: mariadb
driver-class-name: org.mariadb.jdbc.Driver
jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
hibernate:
format_sql: true