server:
  port: 8080

spring:
  application:
    name: stockExchange
  datasource:
    url: jdbc:mariadb://localhost:3306/stock
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # JPA 테이블 생성 후 SQL 실행
  sql:
    init:
      mode: always # 항상 SQL 스크립트 실행
      data-locations: classpath:data.sql
      continue-on-error: true # 에러 발생 시에도 계속 진행