openapi: 3.0.0
info:
  title: API_stockExchange
  description: 주식거래소 REST API 문서
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/seroming/API_stockExchange/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080
  description: 개발 서버
tags:
- name: user
  description: 회원 API
- name: stock
  description: 주식 종목 API
- name: order
  description: 주문 API
- name: execution
  description: 체결 API
- name: holding
  description: 보유 주식 API
paths:
  /api/v1/stock:
    get:
      tags:
      - stock
      summary: 종목 전체 조회
      description: 주식 종목 전체를 조회합니다.
      operationId: getAllStock
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/v1/stock/{stockId}:
    get:
      tags:
      - stock
      summary: 종목 상세 조회
      description: 특정 종목을 상세 조회합니다.
      operationId: getStock
      parameters:
      - name: stockId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
  /api/v1/order:
    get:
      tags:
      - order
      summary: 주문 전체 조회
      description: 주문 목록 전체를 조회합니다.
      operationId: getAllOrder
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
    post:
      tags:
      - order
      summary: 주문 등록
      description: 주문을 등록합니다.
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1_order_body"
        required: true
      responses:
        "201":
          description: 주문 등록 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_201"
        "400":
          description: 잘못된 주문 등록 요청
        "404":
          description: 종목을 찾을 수 없음
  /api/v1/order/{orderId}:
    get:
      tags:
      - order
      summary: 주문 상세 조회
      description: 특정 주문을 상세 조회합니다.
      operationId: getOrder
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_1"
    put:
      tags:
      - order
      summary: 주문 수정
      description: 체결되지 않은 주문을 수정합니다.
      operationId: updateOrder
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/order_orderId_body"
        required: true
      responses:
        "200":
          description: 주문 수정 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_2"
        "400":
          description: 잘못된 주문 수정 요청
        "404":
          description: 주문을 찾을 수 없음
    delete:
      tags:
      - order
      summary: 주문 취소
      description: 체결되지 않은 주문을 취소합니다.
      operationId: deleteOrder
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 주문 취소 성공
        "400":
          description: 이미 체결된 주문은 취소할 수 없습니다.
  /api/v1/holding:
    get:
      tags:
      - holding
      summary: 보유 주식 전체 조회
      description: 보유한 주식 전체를 조회합니다.
      operationId: getAllHolding
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/v1/holding/{holdingId}:
    get:
      tags:
      - holding
      summary: 보유 주식 상세 조회
      description: 특정 보유주식을 상세 조회합니다.
      operationId: getHolding
      parameters:
      - name: holdingId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_3"
  /api/v1/execution:
    get:
      tags:
      - execution
      summary: 체결 내역 전체 조회
      description: 체결 내역 전체를 조회합니다.
      operationId: getAllExecution
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/v1/execution/{executionId}:
    get:
      tags:
      - execution
      summary: 체결 상세 조회
      description: 특정 체결 내역을 상세 조회합니다.
      operationId: getExecution
      parameters:
      - name: executionId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_4"
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        stockId:
          type: integer
        stockName:
          type: string
        stockNumber:
          type: integer
        stockIpo:
          type: string
          enum:
          - KOSPI
          - KOSDAQ
        stockPrice:
          type: integer
    v1_order_body:
      required:
      - orderCount
      - orderPrice
      - orderType
      - stockId
      type: object
      properties:
        stockId:
          type: integer
          description: 주식 종목 id
        orderCount:
          minimum: 1
          type: integer
          description: 주문 수량
        orderPrice:
          type: integer
          description: 주문 가격
        orderType:
          type: string
          description: 주문 타입
          enum:
          - BUY
          - SELL
    inline_response_201:
      type: object
      properties:
        orderId:
          type: integer
        orderCount:
          type: integer
        orderPrice:
          type: integer
        orderType:
          type: string
          enum:
          - BUY
          - SELL
        orderStatus:
          type: string
          enum:
          - PENDING
          - COMPLETED
          - CANCELLED
        orderRemainCount:
          type: integer
        orderExecutedCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        updateAt:
          type: string
          format: date-time
    inline_response_200_1:
      type: object
      properties:
        orderId:
          type: integer
        stockId:
          type: integer
        orderCount:
          type: integer
        orderPrice:
          type: integer
        orderType:
          type: string
          enum:
          - BUY
          - SELL
        orderStatus:
          type: string
          enum:
          - PENDING
          - COMPLETED
          - CANCELLED
        orderRemainCount:
          type: integer
        orderExecutedCount:
          type: integer
        createdAt:
          type: string
          description: 주문 시간
          format: date-time
        updatedAt:
          type: string
          description: 수정 일자
          format: date-time
    order_orderId_body:
      type: object
      properties:
        orderCount:
          minimum: 1
          type: integer
          description: 수정할 주문 수량
          example: 100
        orderPrice:
          type: integer
          description: 수정할 주문 가격
    inline_response_200_2:
      type: object
      properties:
        orderId:
          type: integer
        orderCount:
          type: integer
        orderPrice:
          type: integer
        orderType:
          type: string
          enum:
          - PENDING
          - COMPLETED
          - CANCELLED
        orderRemainCount:
          type: integer
        orderExecutedCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    inline_response_200_3:
      type: object
      properties:
        holdingId:
          type: integer
        stockId:
          type: integer
        stockName:
          type: string
          description: 종목명
        holdingQuantity:
          type: integer
          description: 보유 수량
        holdingTotalPrice:
          type: integer
          description: 총 손익
        currentStockPrice:
          type: integer
          description: 현재 주가
        updatedAt:
          type: string
          format: date-time
    inline_response_200_4:
      type: object
      properties:
        executionId:
          type: integer
        stockId:
          type: integer
        stockName:
          type: string
        executionCount:
          type: integer
          description: 체결 수량
        executionPrice:
          type: integer
          description: 체결 가격
        executionBuyOrderId:
          type: integer
          description: 매수 주문 ID
        executionSellOrderId:
          type: integer
          description: 매도 주문 ID
        createdAt:
          type: string
          description: 체결 시간
          format: date-time
